=== janobrian/lmsgi-asir11-03/XML/dtd/parque.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT parque (estanque* , vial+, mobiliario+)>

<!ELEMENT estanque (animal*)>

<!ATTLIST estanque 
	profundidad CDATA #REQUIRED 
	longitud CDATA #REQUIRED>

<!ELEMENT animal (#PCDATA)>

<!ATTLIST animal 
	fechaEntrada CDATA #REQUIRED 
	especie (tortuga|carpa|pato) #REQUIRED>
	
<!ELEMENT vial (#PCDATA)>

<!ATTLIST vial
	tipoCalzada (calle|senda) #REQUIRED
	longitud CDATA #REQUIRED>
	
<!ELEMENT mobiliario (#PCDATA)>

<!ATTLIST mobiliario
	fechaCompra CDATA #REQUIRED
	proveedor CDATA #REQUIRED
	objeto (banco|silla|tobogÃ¡n|columpio) #IMPLIED >

=== janobrian/lmsgi-asir11-03/XML/parque_con_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE parque SYSTEM "dtd/parque.dtd">

<parque>
	<estanque profundidad="2m" longitud="50m">
		<animal especie="tortuga" fechaEntrada="21/05/2010"/>
		<animal especie="carpa" fechaEntrada="22/05/2010"/>
		<animal especie="pato" fechaEntrada="19/06/2010"/>
	</estanque>
	<vial tipoCalzada="calle" longitud="275m"/>
	<vial tipoCalzada="senda" longitud="13m"/>
	<mobiliario proveedor="ikea" fechaCompra="01/01/2010" objeto="banco"/>
	<mobiliario proveedor="ikea" fechaCompra="01/01/2010" objeto="silla"/>
	<mobiliario proveedor="parques SA" fechaCompra="01/05/2010" objeto="columpio"/>
</parque>
